[package]
name = "lindenmayer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
turtle = "1.0.0-rc.3"
turtle-svg = "0.1.1"
rand = "0.8.4"

[profile.dev.package."*"]
opt-level = 3
